### ISSUE TITLE
admin@sqlsec.com + i神舟战神k610d i7 d2 + 10.13.6 楼主好人一生平安

### ISSUE THREAD

**Issue by kinghammer** [sqlsec/clover#11]
admin@sqlsec.com + i神舟战神k610d i7 d2 + 10.13.6 楼主好人一生平安
万分感谢，下载失败

**Comment by sqlsec** [comment]
已发 Clover版本可能比较低 如果安装不顺利的话 升级clover版本看看 祝黑苹果顺利
