### ISSUE TITLE
2286276539@qq.com G4600 + gt1030 + MSI B250M Motar + 10.13.6 楼主一身平安

### ISSUE THREAD

**Issue by sonyxu** [sqlsec/clover#18]
2286276539@qq.com G4600 + gt1030 + MSI B250M Motar + 10.13.6 楼主一身平安

**Comment by sonyxu** [comment]
还有联想E460 i76500U + R7 M360 + 10.13.6 （高清屏）多谢 麻烦了

**Comment by sqlsec** [comment]
项目没有同款配置 得自己去研究 或者 尝试下载类似配置的clover 😢
