### ISSUE TITLE
Acer VN7-591g Clover 引导花屏

### ISSUE THREAD

**Issue by Hooych** [sqlsec/clover#26]
在进入Clover引导后，显示Apple logo和进度条，进度条读完后花屏

### 基础信息：
* 设备：
<img src="http://res.hualala.com/group2/M01/C9/A3/wKgVT1ukZx2UHYF_ADE5smXCMzw895.jpg" width="600" />

* 使用教程&镜像：
`http://www.sqlsec.com/2018/08/clover.html`

* 替换Clover：
`https://github.com/sqlsec/clover/tree/master/笔记本/Acer宏碁/Acer Aspire VN7-591G+i5-4210H/CLOVER`

### 问题描述：

* 引导
<img src="http://res.hualala.com/group2/M02/22/B3/wKgVSlukZ1epBS-pACSE-B-xHWk900.jpg" width="600" />

* loading
<img src="http://res.hualala.com/group2/M00/C9/70/wKgVT1ukZKHyXBf5ACPs7flMdMk628.jpg" width="600" />

* 花屏
<img src="http://res.hualala.com/group2/M01/C9/AF/wKgVT1ukZ7DqChMNADDGtupWXzY944.jpg" width="600" />

**Comment by sqlsec** [comment]
抱歉 我这边不负责具体的技术细节 只负责提供已有的Clover驱动 👀
引导花屏的话 可以等待显示器休眠的时候 再唤醒看看 可能会正常显示 一般来说安装过后就不会花屏了
