### ISSUE TITLE
下载不了神舟k670e的文件

### ISSUE THREAD

**Issue by DaviesTai** [sqlsec/clover#27]
https://github.com/sqlsec/clover/tree/master/笔记本/神舟/神舟战神K670E-G6D1%2Bi5-7400%2BGTX1050/CLOVER

想要这个里面的文件，萌新要用到efi文件，邮箱daidadalaile@gmail.com

**Comment by sqlsec** [comment]
Clover版本可能比较低 如果安装不顺利的话 升级clover版本看看 祝黑苹果顺利
