### ISSUE TITLE
下载不方便

### ISSUE THREAD

**Issue by wenbke** [sqlsec/clover#76]
Downgit网址打不开，clone整个仓库又太大，还要下载svn才能下载部分文件夹，建议增加zip文件

**Comment by wenbke** [comment]
svn可能也不行，在知乎上找到了方法https://www.zhihu.com/question/25369412

**Comment by sqlsec** [comment]
downgit
其实我项目里面推荐了

**Comment by whidy** [comment]
@sqlsec 似乎不可靠,我正确代理,google什么都OK,用的全局...但是还是下不下来, 如图

![image](https://user-images.githubusercontent.com/2074757/48301335-3c1fc380-e527-11e8-8942-3fb3ce23e6e5.png)

会一直卡这里...并且重试会提示服务器错误之类的

貌似是超出限制了?

![image](https://user-images.githubusercontent.com/2074757/48301351-725d4300-e527-11e8-81ef-dbe664fba187.png)

**Comment by sqlsec** [comment]
@wenbke @whidy  zip文件夹我正在做 目前打算每个clover 配一个zip文件 只能这样了 Coding net会比Github稍微慢一点 不过基本上差不多
