### ISSUE TITLE
Dell  XPS  9550的网卡Killer 1535 驱动解决了吗？

### ISSUE THREAD

**Issue by Beipy** [sqlsec/clover#8]

**Comment by Beipy** [comment]
电脑型号 戴尔 XPS 15 9550 笔记本电脑 
处理器 英特尔 Core i7-6700HQ @ 2.60GHz 四核
主板 戴尔 0N7TVV ( 英特尔 PCI 标准主机 CPU 桥 - 100 Series/C230 Series 芯片组 Family - A14E )
内存 8 GB ( 海力士 DDR4 2133MHz )
主硬盘 希捷 ST1000LM048-2E7172 ( 1 TB / 5400 转/分 )
显卡 Nvidia GeForce GTX 960M ( 2 GB / 戴尔 )
显示器 夏普 SHP1453 ( 15.7 英寸  )
声卡 瑞昱  @ 英特尔 High Definition Audio 控制器
**网卡 Atheros Killer Wireless-n/a/ac 1535 Wireless Network Adapter / Bigfoot Networks**

**Comment by sqlsec** [comment]
那个没有验证过 具体得自己去测试 这些Clover都是大家分享的  你懂得

**Comment by MichaelVector** [comment]
XPS所有的kill网卡都无法驱动，要么插USB网卡要么换，我9560换的DW1830，完美
