### ISSUE TITLE
能帮忙配个<i7-4790>+<技嘉Z97X-UD3H>+<GTX 960>+<10.13.6>的Clover么.

### ISSUE THREAD

**Issue by s7ice** [sqlsec/clover#9]
显卡驱动一直弄不好, 安装好了要么进系统读条一半的时候屏幕直接黑了没信号, 要么显示有了驱动还是一直卡根本没有效果. 都折腾一个礼拜了,下班就一直循环在重启电脑..
通用配置里面的"clover/台式机/i7-4790K+华硕Z97-A+10.13+N卡"这个也没有效果. 4个4790的都试了, 没有效果..

**Comment by s7ice** [comment]
已经解决了 用"i7-4790K+华硕Z97-A+10.13+N卡"这个配置重装的系统
3个跟NV有关的配置组合各种尝试终于好了
最后只开了nvda_drv=1  其他跟NV有关的都关掉了才得以驱动成功。
万分感谢 终于搞定了

**Comment by sqlsec** [comment]
😃 恭喜呀~
